docs: Add WLAN and BLE communication protocol
Filiprogrammer/AlphabotSZUCar pull request #26
Opened 2021-09-12 09:19 UTC by LecraM2003

2021-09-12 10:36 UTC, LecraM2003 commented
#duration: 5

2021-09-12 21:20 UTC, Filiprogrammer requested changes

2021-09-12 21:20 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +</h1>
Use markdown syntax where posible

2021-09-12 21:20 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +                </p>
Remove unnecessary paragraphs

2021-09-12 21:20 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +                    1100 / Remove one by ID
How is the ID of an obstacle determined

2021-09-13 14:43 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +</h1>
changed in new version

2021-09-13 19:19 UTC, Filiprogrammer requested changes

2021-09-13 19:19 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +</table>
Add new line

2021-09-13 19:19 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +### 3.1.2. Bitfeld – 2. Byte (Logging)
Add new line

2021-09-13 19:19 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +# 3. Bitfelder
Add new line

2021-09-13 19:19 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +# 2. BLE Protokoll
Add new line

2021-09-13 19:19 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +</table>
Add new line

2021-09-14 14:55 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                </p>
changed in new version

2021-09-14 15:07 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +</table>
changed in new version

2021-09-14 15:08 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                    1100 / Remove one by ID
every obstacle gets an iterating ID, you can see the ID on the map and when deleting the obstacle, you can either use its ID to remove it, or use the coordinates of the obstacle

2021-09-14 15:09 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +### 3.1.2. Bitfeld – 2. Byte (Logging)
changed in new version

2021-09-14 15:11 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +# 3. Bitfelder
changed in new version

2021-09-14 15:11 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +# 2. BLE Protokoll
changed in new version

2021-09-14 20:39 UTC, Filiprogrammer requested changes

2021-09-14 20:39 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +            <td width="377" colspan="3" valign="top">
Remove valign attribute

2021-09-14 20:39 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +                    <strong>Steuerungsbyte</strong>
Fix identations

2021-09-14 20:39 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +            <td width="152" rowspan="2" valign="top">
Remove width attribute

2021-09-14 20:39 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +<table border="1" cellspacing="0" cellpadding="0">
Remove all table attributes

2021-09-14 20:39 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +                    <strong>Gesamtgröße Byte</strong>
Use &lt;b&gt; instead of &lt;strong&gt;

2021-09-14 20:39 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +<br>
Remove &lt;br&gt; tags as they won't be necessary after removing all table attributes

2021-09-14 20:39 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +                <p align="center">
Remove unnecessary paragraphs

2021-09-14 20:41 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +                    1100 / Remove one by ID
But no ID is sent when adding an obstacle

2021-09-15 16:49 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                    1100 / Remove one by ID
added new command in the new version, which gets sent when a new obstacle was created, this command includes the ID which is iterating generated by the Alphabot

2021-09-15 16:51 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +            <td width="377" colspan="3" valign="top">
changed in new version

2021-09-15 16:52 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                    <strong>Steuerungsbyte</strong>
changed in new version

2021-09-15 16:55 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +            <td width="152" rowspan="2" valign="top">
changed in new version

2021-09-15 16:55 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +<table border="1" cellspacing="0" cellpadding="0">
changed in new version

2021-09-15 16:55 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                    <strong>Gesamtgröße Byte</strong>
changed in new version

2021-09-15 16:56 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +<br>
changed in new version

2021-09-15 16:56 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                <p align="center">
changed in new version

2021-09-15 17:34 UTC, Filiprogrammer requested changes

2021-09-15 17:34 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +                    00 / Ansteuerung
Fix identations

2021-09-15 17:35 UTC, Filiprogrammer requested changes

2021-09-15 17:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +                <p align="center">
No you didn't

2021-09-15 17:42 UTC, Filiprogrammer requested changes

2021-09-15 17:42 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +
Remove unnecessary new line

2021-09-15 17:42 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +
Remove unnecessary new line

2021-09-15 17:42 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +
Remove unnecessary new line

2021-09-15 17:42 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +
Remove unnecessary new line

2021-09-15 17:42 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +
Remove unnecessary new line

2021-09-17 06:41 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                <p align="center">
changed in new version

2021-09-17 10:55 UTC, Filiprogrammer requested changes

2021-09-17 10:55 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +            <td  rowspan="2" >
Remove unnecessary space between td and rowspan

2021-09-20 08:26 UTC, Filiprogrammer reviewed
Maybe describe every packet type in its own table. (Like in https://wiki.vg/Protocol)

Something like this:

### Speed & Steer (Packet ID: 0x00)

| Field Name | Field Type  |                            Notes                            |
|------------|-------------|-------------------------------------------------------------|
|   Speed    | Signed Byte | The desired speed (-127 is backward, 127 is forward)        |
|   Steer    | Signed Byte | The desired steering direction (-127 is left, 127 is right) |

This would probably make it a lot more readable.

2021-09-21 09:49 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                Anzahl der Steps sbyte (1B) + Speed in sbyte (1B)
Better definition of what is left and right

2021-09-21 09:55 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                01 / Kartengröße
not necessary

2021-09-21 09:55 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                01 / Kartengröße
not necessary

2021-09-22 16:57 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +            <td  rowspan="2" >
not necessary anmore, cause i used markdown only now

2021-09-22 16:58 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                Anzahl der Steps sbyte (1B) + Speed in sbyte (1B)
changed in new version

2021-09-22 16:58 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                01 / Kartengröße
removed in new version

2021-09-22 16:58 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +                01 / Kartengröße
removed in new version

2021-09-24 08:35 UTC, Filiprogrammer requested changes

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Time       | int64       | The time when the packet was sent |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Calibration Type | int8        | 0x00 for calibration finished; 0x01 for steering; 0x02 for automatical compass calibration; 0x03 for manual compass calibration; 0x04 for compass offset|
Add space at the end of the last cell

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Calibration Type | int8        | 0x00 for calibration finished; 0x01 for steering; 0x02 for automatical compass calibration; 0x03 for manual compass calibration; 0x04 for compass offset|
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| ID         | uint8       | The ID of the obstacle (gets set by the Alphabot) |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| ID         | uint8       | The ID of the obstacle; if the value is 0xFF all obstacles will be cleared |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Distance   | uint16      | The distance in centimetres |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Height     | uint16      | The height in centimetres       |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Time       | int64       | The time when the packet was sent |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Distance   | uint16      | The distance in centimetres |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Position Y | int16       | The y coordinate in centimetres |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| ID         | uint8       | ID of the obstacle              |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Height     | uint16      | The height in centimetres       |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Position Y | int16       | The y coordinate in centimetres |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Position Y | int16       | The y coordinate in centimetres |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Time       | int64       | The time when the packet gets sent |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Degree     | int16       | The degree of the sensor |
Remove empty space after "Field Type" column

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +# 1. WLAN – bitbased protocol
Write bit based as two words

2021-09-24 08:35 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Time       | int64       | The time when the packet gets sent |
Specify that the timestamp should be in milliseconds since midnight January 1, 1970 UTC.

2021-09-24 08:37 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Position Y | int16       | The y coordinate in centimetres |
What happens when multiple obstacles overlap?

2021-09-24 08:42 UTC, Filiprogrammer requested changes

2021-09-24 08:42 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +### Remove one obstacle by Position (Packet ID: 0x0B)
Write "position" with a lowercase "p" at the beginning

2021-09-24 08:42 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +## 1.2. Responses (Alphabot to Client)
Write "client" with a lowercase "c"

2021-09-24 08:42 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +At first Position, Width and Height is sent by the Client, the Alphabot will answer with the data and the ID.
Fix casing to comply with English grammar.

2021-09-24 09:04 UTC, Filiprogrammer requested changes
Since the packet ID does not occupy all bits of the first byte, use some bits to encode a protocol version.

2021-09-24 09:28 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Speed      | int8       | The desired speed (negative values indicate backward driving, positive values forward driving)                   |
changed in new version

2021-09-24 09:29 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +see [3.1. Toggle bit field](#3.1.)
changed in new version

2021-09-24 09:30 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +## 3.1. Toggle - Bitfield
changed in new version

2021-09-24 09:30 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +### 3.1.2. Bitfield – 2. Byte (Logging)
changed in new version

2021-09-24 09:30 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +# 3. Bitfields
changed in new version

2021-09-24 09:31 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +### 3.1.1. Bitfield – 1. Byte (Einstellungen)
changed in new version

2021-09-24 09:31 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +see [3.1. Toggle bit field](#3.1.)
changed in new version

2021-09-24 09:31 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Time       | int64       | The time when the packet was sent |
changed in new version

2021-09-24 09:32 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Position Y | int16       | The y coordinate in centimetres |
changed in new version

2021-09-24 09:32 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Calibration Type | int8        | 0x00 for calibration finished; 0x01 for steering; 0x02 for automatical compass calibration; 0x03 for manual compass calibration; 0x04 for compass offset|
changed in new version

2021-09-24 09:33 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Calibration Type | int8        | 0x00 for calibration finished; 0x01 for steering; 0x02 for automatical compass calibration; 0x03 for manual compass calibration; 0x04 for compass offset|
changed in new version

2021-09-24 09:34 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +see [3.2. Sensor packets](#3.2.)
changed in new version

2021-09-24 09:34 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| ID         | uint8       | The ID of the obstacle (gets set by the Alphabot) |
changed in new version

2021-09-24 09:34 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| ID         | uint8       | The ID of the obstacle; if the value is 0xFF all obstacles will be cleared |
changed in new version

2021-09-24 09:35 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Distance   | uint16      | The distance in centimetres |
changed in new version

2021-09-24 09:35 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Height     | uint16      | The height in centimetres       |
changed in new version

2021-09-24 09:36 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Time       | int64       | The time when the packet was sent |
changed in new version

2021-09-24 09:36 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Distance   | uint16      | The distance in centimetres |
changed in new version

2021-09-24 09:36 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Position Y | int16       | The y coordinate in centimetres |
changed in new version

2021-09-24 09:37 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| ID         | uint8       | ID of the obstacle              |
changed in new version

2021-09-24 09:37 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Height     | uint16      | The height in centimetres       |
changed in new version

2021-09-24 09:37 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Position Y | int16       | The y coordinate in centimetres |
changed in new version

2021-09-24 09:37 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Position Y | int16       | The y coordinate in centimetres |
changed in new version

2021-09-24 09:38 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Time       | int64       | The time when the packet gets sent |
changed in new version

2021-09-24 09:38 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Degree     | int16       | The degree of the sensor |
changed in new version

2021-09-24 09:38 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +# 1. WLAN – bitbased protocol
changed in new version

2021-09-24 09:44 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Time       | int64       | The time when the packet gets sent |
changed in new version

2021-09-24 09:55 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Position Y | int16       | The y coordinate in centimetres |
If there are multiple objects on the same position, all of them will be removed.
This text is added in the new version.

2021-09-24 09:55 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +### Remove one obstacle by Position (Packet ID: 0x0B)
changed in new version

2021-09-24 09:56 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +## 1.2. Responses (Alphabot to Client)
changed in new version

2021-09-24 09:57 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +At first Position, Width and Height is sent by the Client, the Alphabot will answer with the data and the ID.
changed in new version

2021-09-24 09:59 UTC, LecraM2003 reviewed
implement WIP texts (path finding)

2021-09-24 10:57 UTC, LecraM2003 reviewed
Add Alphabot response for error messages (wrong protocol version, wrong packet id, wrong payload)

2021-09-24 15:43 UTC, LecraM2003 commented
I think the Alphabot needs to send the Toggle Settings too, so the Alphabot can actually "toggle" it. The client first has to get the toggle settings to see which are activated and which not. Should I implement that in the protocol? @Filiprogrammer

2021-09-24 22:31 UTC, Filiprogrammer requested changes

2021-09-24 22:31 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +see [3.1. Toggle bit field](#31-toggle---bitfield)
Change text in round brackets to "#31-toggle---bit-field"

2021-09-24 22:33 UTC, Filiprogrammer requested changes

2021-09-24 22:33 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +### Distance sensor response (BLE Packet ID: 0x01)
BLE uses UUIDs

2021-09-24 22:37 UTC, Filiprogrammer commented
> 
> 
> I think the Alphabot needs to send the Toggle Settings too, so the Alphabot can actually "toggle" it. The client first has to get the toggle settings to see which are activated and which not. Should I implement that in the protocol? @Filiprogrammer

Makes sense. Are you thinking of making the Alphabot automatically send the toggles upon a new client connection?

2021-09-24 22:49 UTC, Filiprogrammer requested changes
Add an invitation feature to the protocol specification.
Once a client is connected, new clients are usually not accepted unless the connected client enabled an "invite" toggle. This toggle should only be enabled until another client connects or the toggle is manually disabled.

2021-09-27 15:08 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +The last 3 bits (MSB) of the packet header define the protocol version. The currently only version is 000.
changed in new version

2021-09-27 15:09 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +If there are multiple objects on the same position, all of them will be removed.
changed in new version

2021-09-27 15:10 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Error ID       | uint8              | The error ID, see [3.4.](#34Error-id-format)   |
changed in new version

2021-09-27 15:10 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Error ID       | uint8              | The error ID, see [3.4.](#34Error-id-format)   |
changed in new version

2021-09-27 15:11 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +see [3.1. Toggle bit field](#31-toggle---bitfield)
changed in new version

2021-09-27 15:19 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +### Distance sensor response (BLE Packet ID: 0x01)
yes, but we dont have infinite characteristics, so the BLE_CHAR_SENSOR characteristic is used for all sensor values, the client enters the BLE Packet ID in the first byte, the following bytes are the answer by the Alphabot

2021-09-27 15:20 UTC, LecraM2003 commented
> Add an invitation feature to the protocol specification.
> Once a client is connected, new clients are usually not accepted unless the connected client enabled an "invite" toggle. This toggle should only be enabled until another client connects or the toggle is manually disabled.

Already done... see #3.1 Toggle Requests

2021-09-27 15:25 UTC, LecraM2003 commented
> > I think the Alphabot needs to send the Toggle Settings too, so the Alphabot can actually "toggle" it. The client first has to get the toggle settings to see which are activated and which not. Should I implement that in the protocol? @Filiprogrammer
> 
> Makes sense. Are you thinking of making the Alphabot automatically send the toggles upon a new client connection?

Yes, I changed that in the new version

2021-09-28 07:32 UTC, Filiprogrammer requested changes

2021-09-28 07:32 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +the Alphabot changes a setting by himself.
The Alphabot is neuter. Therefore change "himself" to "itself".

2021-09-28 07:32 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +The toggle settings get automatically sent upon a new client connection, but they will aso be sent if
Fix the spelling mistake in the word "also".

2021-09-28 12:14 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +the Alphabot changes a setting by himself.
changed in new version

2021-09-28 12:14 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +The toggle settings get automatically sent upon a new client connection, but they will aso be sent if
changed in new version

2021-09-29 16:45 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +### Distance sensor response (BLE Packet ID: 0x01)
its possible now (in the new version), that you can send multiple sensor values in one BLE characteristic

2021-09-29 20:28 UTC, Filiprogrammer requested changes

2021-09-29 20:28 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +The position will be splitted in 3 bytes, 12 bit per coordinate
Change "splitted in" to "split into"

2021-09-29 20:28 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +### Distance sensor response (Sensor type: 01)
Either add a "0b" prefix to the binary value or use decimal numbers.

2021-09-29 20:28 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +| Degree     | int8       | The measured degree divided by 2 |
I think we can afford to use 2 bytes here.

2021-09-29 20:32 UTC, Filiprogrammer requested changes

2021-09-29 20:32 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +In the WLAN protocol, the packet 0x05 is followed by a 2-byte bit field.
Use "WiFi" instead of "WLAN" as this indicates that we are using the IEEE 802.11 standard.

2021-09-29 20:32 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +# 1. WLAN – bit based protocol
Use "WiFi" instead of "WLAN" as this indicates that we are using the IEEE 802.11 standard.

2021-09-29 20:39 UTC, Filiprogrammer requested changes
Change file name to snake_case.

2021-09-30 12:40 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +The position will be splitted in 3 bytes, 12 bit per coordinate
changed in new version

2021-09-30 12:41 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +### Distance sensor response (Sensor type: 01)
changed into "0b" in new version

2021-09-30 12:42 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Degree     | int8       | The measured degree divided by 2 |
changed to 2 bytes for more accuracy in new version

2021-09-30 12:43 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +In the WLAN protocol, the packet 0x05 is followed by a 2-byte bit field.
changed in new version

2021-09-30 12:43 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +# 1. WLAN – bit based protocol
changed in new version

2021-09-30 18:30 UTC, Filiprogrammer commented on docs/WLAN-BLE communication protocol.md
> +### Distance sensor response (Sensor type: 01)
You added a "b" suffix instead of a "0b" prefix.

2021-09-30 20:41 UTC, Filiprogrammer requested changes

2021-10-01 09:11 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +| Degree     | int16      | The degree of the sensor |
Change to int8

2021-10-01 10:20 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +### Distance sensor response (Sensor type: 01)
oopsie, changed in new version

2021-10-01 10:26 UTC, LecraM2003 commented on docs/WLAN-BLE communication protocol.md
> +| Degree     | int16      | The measured degree |
changed in new version

2021-10-01 10:56 UTC, Filiprogrammer requested changes

2021-10-01 10:56 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +If the degree value corresponds to no sensor, an error will be sent back (WrongPayloadError).
Change "WrongPayloadError" to a consistent format.

2021-10-01 10:56 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +| Degree     | int16      | The degree of the sensor (0-359) |
Specify which degree value corresponds to which direction.

2021-10-01 10:56 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +| Degree     | int16      | The measured degree (0-359) |
Specify which degree value corresponds to which direction.

2021-10-01 10:56 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +| Degree     | int16      | The degree of the sensor (0-359) |
Specify which degree value corresponds to which direction.

2021-10-01 10:56 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +| Degree     | uint8      | The degree of the sensor divided by 2 (0-179) |
Specify which degree value corresponds to which direction.

2021-10-01 10:56 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +| Degree     | int16      | The measured degree (0-359) |
Specify which degree value corresponds to which direction.

2021-10-01 14:51 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +| Degree     | int16      | The measured degree (0-359) |
described in new version

2021-10-01 14:51 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +| Degree     | int16      | The degree of the sensor (0-359) |
described in new version

2021-10-01 14:51 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +| Degree     | uint8      | The degree of the sensor divided by 2 (0-179) |
described in new version

2021-10-01 14:51 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +| Degree     | int16      | The measured degree (0-359) |
described in new version

2021-10-01 21:12 UTC, Filiprogrammer requested changes

2021-10-01 21:12 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +In the first byte 0b01 is sent twice, because two distance sensor packets will follow, the following bits in the first two byte are filled with 0. Byte 2 and 3 represent the payload of the first dist
Add an "s" at the end of "in the first two byte"

2021-10-01 21:12 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +The first two bytes describe the packet types that will follow. Then the payload of these packets will follow. There can be multiple sensor responses sent at a time. The following responses can be se
Change "packet types" to "sensor types"

2021-10-02 07:31 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +In the first byte 0b01 is sent twice, because two distance sensor packets will follow, the following bits in the first two byte are filled with 0. Byte 2 and 3 represent the payload of the first dist
changed in new version

2021-10-02 07:31 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +The first two bytes describe the packet types that will follow. Then the payload of these packets will follow. There can be multiple sensor responses sent at a time. The following responses can be se
changed in new version

2021-10-02 08:37 UTC, Filiprogrammer approved these changes

2021-10-02 08:38 UTC, merged