README: Add QEMU build instructions for Windows
Filiprogrammer/AlphabotSZUCar pull request #34
Opened 2021-09-28 19:51 UTC by Filiprogrammer

2021-09-29 16:49 UTC, LecraM2003 approved these changes

2021-09-30 13:14 UTC, LecraM2003 requested changes

2021-09-30 13:14 UTC, LecraM2003 commented on README.md
> +Install cygwin key and add cygwin sources.
Change "." to ":"

2021-09-30 13:14 UTC, LecraM2003 commented on README.md
> +Install packages.
Change "." to ":"

2021-09-30 13:14 UTC, LecraM2003 commented on README.md
> +Patch gversionmacros.h to work with other versions of glibc.
Change "." to ":"

2021-09-30 13:14 UTC, LecraM2003 commented on README.md
> +Patch configure script to work with other versions of glibc.
Change "." to ":"

2021-09-30 13:14 UTC, LecraM2003 commented on README.md
> +Workaround for buggy cross pkg-config
Add ":" at the end of the line

2021-09-30 13:14 UTC, LecraM2003 commented on README.md
> +Create header files for WHPX API.
Change "." to ":"

2021-09-30 13:14 UTC, LecraM2003 commented on README.md
> +Build QEMU for Windows.
Change "." to ":"

2021-09-30 13:14 UTC, LecraM2003 commented on README.md
> +Copy all the DLLs.
Change "." to ":"

2021-10-02 09:36 UTC, LecraM2003 approved these changes

2021-10-02 09:36 UTC, merged

2021-10-02 09:38 UTC, Filiprogrammer commented
#duration: 2