Implement client library (TCP-Windows)
Filiprogrammer/AlphabotSZUCar pull request #35
Opened 2021-10-08 11:41 UTC by LecraM2003

2021-10-08 11:42 UTC, LecraM2003 commented
#duration: 2

2021-10-19 17:30 UTC, Filiprogrammer requested changes

2021-10-19 17:30 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateCompassRequest.cs
> +            setCompassOffset = 0x04
Use PascalCase for enums.

2021-10-19 17:30 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Obstacle.cs
> +            //if the id is 65535, it was not set in constructor and will not be added in array
```suggestion
            // If the id is 65535, it was not set in constructor and will not be added to the array.
```

2021-10-19 17:30 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Position.cs
> +        public short PositionX { get; private set; }
Add an empty line

2021-10-19 17:30 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/SpeedSteerRequest.cs
> +            ret[0] = 0x01; //Packet ID 0x01
Add a space between double slahes and comment

```suggestion
            ret[0] = 0x01; // Packet ID 0x01
```

2021-10-19 17:30 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ToggleRequest.cs
> +            bytes[1] = temp;
Use the correct order in the first place.

2021-10-19 17:30 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ToggleResponse.cs
> +            DoCompassCalibration = bitArray[15];
Seems like the bytes are swapped.

2021-10-19 17:30 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
> +            byte[] expectedBytes = { 9, 40,0, 27, 41, 159, 1 , 101, 0};
Use hex values.

2021-10-20 06:41 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PathFindingResponse.cs
> +            right = 0x07
changed in new version

2021-10-20 06:42 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateCompassRequest.cs
> +            setCompassOffset = 0x04
changed in new version

2021-10-20 06:45 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Position.cs
> +        public short PositionX { get; private set; }
changed in new version

2021-11-02 13:04 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ToggleResponse.cs
> +            DoCompassCalibration = bitArray[15];
ok

2021-11-02 13:28 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ToggleRequest.cs
> +            bytes[1] = temp;
not necessary right now, other stuff has higher priority, create an issue so the problem will  be eventually solved when time is available

2021-11-02 13:28 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
> +            byte[] expectedBytes = { 9, 40,0, 27, 41, 159, 1 , 101, 0};
done

2021-11-02 14:20 UTC, Filiprogrammer requested changes

2021-11-02 14:20 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Position.cs
> +                throw new ArgumentException("The array must contain of 4 elements");
```suggestion
                throw new ArgumentException("The array must consist of 4 elements");
```

2021-11-02 14:20 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Position.cs
> +            PositionY = (short)(posYBytes[0] | (posYBytes[1] << 8));
The byte arrays called "posXBytes" and "posYBytes" seem unnecessary.
```suggestion
            PositionX = (short)(bytes[0] | (bytes[1] << 8));
            PositionY = (short)(bytes[2] | (bytes[3] << 8));
```

2021-11-02 14:20 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ConfigurePositioningAnchorRequest.cs
> +            byte[] ret = new byte[5];
The allocation of this byte array is unnecessary, since it is overwritten later.

2021-11-02 14:20 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/PingRequest.cs
> +
Remove the blank line.
```suggestion
```

2021-11-02 14:20 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/NavigationTargetRequest.cs
> +
Remove this blank line.
```suggestion
```

2021-11-02 14:20 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveObstacleRequest.cs
> +                ret = packetId.Concat(positionData).ToArray();
Reduce the number of blank lines.

2021-11-07 17:15 UTC, LecraM2003 commented on .gitignore
> +clients/AlphabotClientLibrary/AlphabotClientLibrary/IHateMicrosoft/
done

2021-11-07 17:18 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateCompassRequest.cs
> +            return ret;
done

2021-11-07 17:19 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/AddObstacleRequest.cs
> +            return packetId.Concat(obstacleData).ToArray();
done

2021-11-07 17:19 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
> +            return new CompassResponse(degree);
done

2021-11-07 17:20 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Core.Ble/BleSensorResponse.cs
> +            _sensorPackets.Add(new PositioningResponse(new Shared.Models.Position(posX, posY)));
done

2021-11-07 17:22 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Core.Ble/BleSensorResponse.cs
> +            ushort distance = (ushort)(bytes[1] * 2);
done

2021-11-07 17:23 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Core.Ble/BleSensorResponse.cs
> +            short posY = (short) (((bytes[1] & 0xF0) >> 4) | (bytes[2] << 4));
done

2021-11-07 17:28 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Core.Ble/BleSensorResponse.cs
> +            short degree = (short)(bytes[0] | ((bytes[1] << 8) & 0x0F));
done by myself

2021-11-07 17:31 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
> +            degree = (short)(degreeBytes[0] | (degreeBytes[1] << 8));
done

2021-11-07 17:34 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ConfigurePositioningAnchorRequest.cs
> +            byte[] ret = new byte[5];
done

2021-11-07 17:34 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ConfigurePositioningAnchorRequest.cs
> +            return ret;
done

2021-11-07 17:37 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveObstacleRequest.cs
> +                ret = packetId.Concat(positionData).ToArray();
done

2021-11-07 17:38 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ErrorResponse.cs
> +            Error = errorType;
done

2021-11-07 17:39 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PathFindingResponse.cs
> +
done

2021-11-08 15:57 UTC, Filiprogrammer requested changes

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IAlphabotRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IAlphabotResponse.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IConnectionData.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Contracts/IResponseInterpreter.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/BleConnectionData.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
using System.Net.NetworkInformation;
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/BleInformation.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Obstacle.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Position.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/WiFiConnectionData.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
using System.Net;
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/RequestInterpreter.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/AddObstacleRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
using System.Linq;
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateCompassRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateSteeringRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ConfigurePositioningAnchorRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
using System.Linq;
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/DistanceSensorRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/NavigationTargetRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
using System.Linq;
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/PingRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
using System.Linq;
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveAllObstaclesRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/RemoveObstacleRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
using System.Linq;
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/SpeedSteerRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/TestRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ToggleRequest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/ResponseInterpreter.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/CompassResponse.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/DistanceSensorResponse.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ErrorResponse.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/MultipleSensorResponse.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/NewObstacleRegisteredResponse.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PathFindingResponse.cs
> +using AlphabotClientLibrary.Shared.Models;
Remove unnecessary using directives.
```suggestion
using AlphabotClientLibrary.Shared.Contracts;
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PingResponse.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/PositioningResponse.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/TestResponse.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/ToggleResponse.cs
> +using AlphabotClientLibrary.Shared.Models;
Remove unnecessary using directives.
```suggestion
using AlphabotClientLibrary.Shared.Contracts;
```

2021-11-08 15:57 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
> +using System.Threading.Tasks;
Remove unnecessary using directives.
```suggestion
```

2021-11-08 16:41 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Core.Ble/BleResponseInterpreter.cs
> +
done

2021-11-09 10:16 UTC, Filiprogrammer requested changes
Refactor BLE sensor response

2021-11-09 10:16 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/MultipleSensorResponse.cs
> +        public List<IAlphabotResponse> SensorResponses { get; private set; }
```suggestion
    {
        public enum SensorType
        {
            None,
            DistanceSensor,
            Positioning,
            Compass
        }

        public List<IAlphabotResponse> SensorResponses { get; private set; }
```

2021-11-15 12:16 UTC, Filiprogrammer requested changes

2021-11-15 12:16 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpHandlerWindows.cs
> +        public TcpHandlerWindows() : base (new ResponseHandler()) { }
```suggestion
        public TcpHandlerWindows() : base(new ResponseHandler()) { }
```

2021-11-15 12:16 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpHandlerWindows.cs
> +
Remove indenting spaces on empty line

2021-11-15 12:16 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
> +using AlphabotClientLibrary.Shared.Models;
Remove unused using directive
```suggestion
```

2021-11-15 12:16 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
> +            Array.Copy(bytes, 1, DataBytes, 0, bytes.Length-1);
```suggestion
            Array.Copy(bytes, 1, DataBytes, 0, bytes.Length - 1);
```

2021-11-15 12:16 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Models/Position.cs
> +            if(bytes.Length != 4)
```suggestion
            if (bytes.Length != 4)
```

2021-11-15 12:16 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/CalibrateCompassRequest.cs
> +            switch(_compassCalibrationType)
```suggestion
            switch (_compassCalibrationType)
```

2021-11-15 12:16 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ToggleRequest.cs
> +        private byte[] ConvertTogglesToBytes()
```suggestion
        private byte[] ConvertTogglesToBytes()
```

2021-11-15 12:16 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/ResponseInterpreter.cs
> +            {
```suggestion
            {
```

2021-11-15 12:16 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/NewObstacleRegisteredResponse.cs
> +
Remove indenting spaces on empty line

2021-11-15 12:44 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpHandlerWindows.cs
> +
done

2021-11-15 12:44 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/NewObstacleRegisteredResponse.cs
> +
done

2021-11-15 13:06 UTC, Filiprogrammer approved these changes

2021-11-15 13:13 UTC, merged