Make TCP and BLE protocol functionality the same
Filiprogrammer/AlphabotSZUCar pull request #44
Opened 2021-11-07 18:52 UTC by LecraM2003

To make the TCP and BLE protocol functionality the same following things were changed:

- It is now possible to remove ALL obstacles by sending 0 bytes in the RemoveObstacle characteristic
- It is now possible to configure the positioning anchors in a new added characteristic

Also some not visible spacing was fixed.

2021-11-07 18:53 UTC, LecraM2003 commented
#duration: 0.5

2021-11-13 16:55 UTC, Filiprogrammer requested changes

2021-11-13 16:55 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +### BLE_CHAR_ANCHORS_LOCATION (UUID: 8a55dd30-463b-40f6-8f21-d68efcc386b2)
```suggestion
### BLE_CHAR_ANCHOR_LOCATIONS (UUID: 8a55dd30-463b-40f6-8f21-d68efcc386b2)
```

2021-11-13 16:55 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
>  The Alphabot will set all values to 0 when the deletion is finished.
How does that server respond when the client sends 0 bytes to remove all obstacles?
Maybe we could specify that the server always responds with one 0 byte... 🤔

2021-11-13 16:55 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> -
Why did you change the order?

2021-11-13 17:08 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> -
Because I want the smaller table to come first for better readability

2021-11-13 17:20 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
>  The Alphabot will set all values to 0 when the deletion is finished.
done in new commit

2021-11-13 20:08 UTC, Filiprogrammer requested changes

2021-11-14 10:45 UTC, Filiprogrammer reviewed
Under the WiFi based protocol, the server sends nothing when the calibration is complete. Meanwhile the BLE based protocol specifies that the server sends a 0x00 on BLE_CHAR_CALIBRATE to indicate that calibration has finished.

Marcel: changed that, so the BLE_CHAR_CALIBRATE doesnt send 0x00 anymore if its finished

2021-11-14 19:44 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
>  | 0x03          | unknown packet id                 |
done

2021-11-15 13:11 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +| Calibration Type | int8        | 0x00 for stopping manual compass calibration; 0x01 for steering; 0x02 for automatic compass calibration; 0x03 for manual compass calibration; 0x04 for compass offse
It would be prefered to have it consistent with the WiFi based protocol

* 0x00 to calibrate steering
* 0x01 for automatic compass calibration
* 0x02 to start manual compass calibration
* 0x03 to end manual compass calibration
* 0x04 to set compass offset

2021-11-15 13:35 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +| Calibration Type | int8        | 0x00 for stopping manual compass calibration; 0x01 for steering; 0x02 for automatic compass calibration; 0x03 for manual compass calibration; 0x04 for compass offse
done

2021-11-15 14:42 UTC, Filiprogrammer submitted a review, later dismissed

2021-11-15 19:09 UTC, Filiprogrammer approved these changes

2021-11-15 19:19 UTC, merged