Adapt client library to new protocol changes
Filiprogrammer/AlphabotSZUCar pull request #48
Opened 2021-11-15 14:00 UTC by LecraM2003

Changes made:

- Implement RemoveAllObstacles request in BLE
- Implement ConfigureAnchorLocations request in BLE
- Change calibration types in BLE

2021-11-15 14:00 UTC, LecraM2003 commented
#duration: 0.5

2021-11-16 09:32 UTC, Filiprogrammer requested changes

2021-11-16 09:42 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/ConfigurePositioningAnchorRequest.cs
> +            }
done

2021-11-16 09:44 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Requests/NavigationTargetRequest.cs
>          }
done

2021-11-16 09:55 UTC, Filiprogrammer approved these changes

2021-11-16 09:58 UTC, merged