Fix positioning response interpretation
Filiprogrammer/AlphabotSZUCar pull request #52
Opened 2021-11-16 14:59 UTC by LecraM2003

Because it was accidently removed, when removing the request packet 0x02 in TCP

2021-11-16 22:06 UTC, Filiprogrammer requested changes

2021-11-16 22:06 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
> +
Remove empty line

2021-11-17 10:42 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
> +
done, even though I dont like it

2021-11-17 20:25 UTC, Filiprogrammer approved these changes

2021-11-17 20:33 UTC, merged