Client library tcp unit tests
Filiprogrammer/AlphabotSZUCar pull request #53
Opened 2021-11-16 15:12 UTC by LecraM2003

Adds tcp requests and responses unit tests (the position response test will fail if #52 is not merged into main already)
@Filiprogrammer Maybe its possible to include these tests 
![image](https://user-images.githubusercontent.com/22198605/142011528-53eb48f6-ffc6-40f6-b484-2d62ae015900.png)

2021-11-16 15:16 UTC, LecraM2003 commented
#duration: 9

2021-11-16 22:29 UTC, Filiprogrammer requested changes

2021-11-16 22:29 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            if (response is ToggleResponse)
Use `Assert.True(response is ToggleResponse)` instead

2021-11-16 22:29 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            if (response is PositioningResponse)
Assert whether the response is of the correct type instead of using an if statement.

2021-11-16 22:29 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            if (response is PingResponse)
Assert whether the response is of the correct type instead of using an if statement.

2021-11-16 22:29 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            if (response is PathFindingResponse)
Assert whether the response is of the correct type instead of using an if statement.

2021-11-16 22:29 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            if (response is NewObstacleRegisteredResponse)
Assert whether the response is of the correct type instead of using an if statement.

2021-11-16 22:29 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            if (response is ErrorResponse)
Assert whether the response is of the correct type instead of using an if statement.

2021-11-16 22:29 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            if (response is DistanceSensorResponse)
Assert whether the response is of the correct type instead of using an if statement.

2021-11-16 22:29 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            if (response is CompassResponse)
Assert whether the response is of the correct type instead of using an if statement.

2021-11-17 10:50 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            if (response is ToggleResponse)
done

2021-11-17 10:50 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            if (response is PositioningResponse)
done

2021-11-17 10:53 UTC, LecraM2003 commented
All tests passed, except the TestPositioningResponse, because #52 isn't merged into main yet. (Would work if its merged)

![image](https://user-images.githubusercontent.com/22198605/142187343-a1a408dc-1fff-44bf-8e0b-b98896771b93.png)

2021-11-17 22:05 UTC, Filiprogrammer requested changes

2021-11-17 22:05 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
> +            Assert.True(difference >= 0 && difference < 1000, "The time difference was greater than 1000ms");
```suggestion
            PingRequest request = new PingRequest();
            long currentTime = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
            byte[] requestArr = new byte[8];

            Array.Copy(request.GetBytes(), 1, requestArr, 0, 8);
            long requestTime = BitConverter.ToInt64(requestArr);
            long difference = requestTime - currentTime;

            Assert.True(difference >= 0 && difference < 1000, "The time difference was greater than 1000ms");
```

2021-11-17 22:05 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
> +
```suggestion
```

2021-11-17 22:05 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpRequestTest.cs
> +            Assert.Equal(expectedBytesRemoveByPos, requestRemoveByPos.GetBytes());
Split this up into two tests

2021-11-17 23:23 UTC, Filiprogrammer requested changes

2021-11-17 23:23 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.sln
> +		{A3437C37-F7AB-4117-B2F7-F75F8A5A1F2E}.Release|x86.Build.0 = Release|Any CPU
```suggestion
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{8D886359-AF08-41D4-95E7-322BDF0D1935}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{8D886359-AF08-41D4-95E7-322BDF0D1935}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{8D886359-AF08-41D4-95E7-322BDF0D1935}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{8D886359-AF08-41D4-95E7-322BDF0D1935}.Release|Any CPU.Build.0 = Release|Any CP
		{14E3703B-1901-4C67-AC93-44192FB92449}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{14E3703B-1901-4C67-AC93-44192FB92449}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{14E3703B-1901-4C67-AC93-44192FB92449}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{14E3703B-1901-4C67-AC93-44192FB92449}.Release|Any CPU.Build.0 = Release|Any CP
		{182A9A8C-8D44-4389-B035-35067D283A7D}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{182A9A8C-8D44-4389-B035-35067D283A7D}.Debug|Any CPU.Build.0 = Debug|Any CP
		{182A9A8C-8D44-4389-B035-35067D283A7D}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{182A9A8C-8D44-4389-B035-35067D283A7D}.Release|Any CPU.Build.0 = Release|Any C
		{A3437C37-F7AB-4117-B2F7-F75F8A5A1F2E}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{A3437C37-F7AB-4117-B2F7-F75F8A5A1F2E}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{A3437C37-F7AB-4117-B2F7-F75F8A5A1F2E}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{A3437C37-F7AB-4117-B2F7-F75F8A5A1F2E}.Release|Any CPU.Build.0 = Release|Any CPU
```

2021-11-19 11:11 UTC, Filiprogrammer requested changes

2021-11-19 11:11 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/AlphabotClientLibrary.Test.csproj
> +    </PackageReference>
```suggestion
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
```

2021-11-19 11:27 UTC, Filiprogrammer approved these changes

2021-11-19 11:37 UTC, merged