Simple tcp test client and server application
Filiprogrammer/AlphabotSZUCar pull request #54
Opened 2021-11-16 15:48 UTC by LecraM2003

For testing connection, sending and receiving of packages.

Should look like this:
![image](https://user-images.githubusercontent.com/22198605/142018120-7d40c547-f3b7-4bc4-a553-bfc0168bdb09.png)

Closes #40

2021-11-16 15:49 UTC, LecraM2003 commented
#duration: 1.5

2021-12-03 22:08 UTC, Filiprogrammer requested changes

2021-12-03 22:08 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Server/Program.cs
> +                    Console.WriteLine("[CONNECTION]: Received following bytes: " + receivedBytes);
```suggestion
                    StringBuilder receivedBytes = new StringBuilder("[CONNECTION]: Received the following bytes:");

                    foreach (var receivedByte in msg)
                        sentBytes.AppendFormat(" 0x{0,2:X2},", receivedByte);

                    Console.WriteLine(receivedBytes.ToString());
```

2021-12-03 22:08 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test.Tcp.Server/Program.cs
> +                    Console.Write("[CONNECTION]: Put in the id you want to respond: ");
```suggestion
                    Console.Write("[CONNECTION]: Enter the id you want to respond: ");
```

2021-12-07 18:22 UTC, Filiprogrammer approved these changes

2021-12-07 18:24 UTC, merged