Client example WinForms TCP
Filiprogrammer/AlphabotSZUCar pull request #55
Opened 2021-11-16 16:18 UTC by LecraM2003

Create a simple GUI as an example how to use the client library with TCP on WindowsForms

Currently it only supports: connecting, deconnecting, steering and changing speed
Works with an Alphabot that is compatible with the new protocol (#38)

GUI:
![image](https://user-images.githubusercontent.com/22198605/142022866-baad3f53-dafd-4f71-8893-3103c1eb7775.png)

2021-11-16 16:19 UTC, LecraM2003 commented
#duration: 4

2021-11-19 12:27 UTC, Filiprogrammer requested changes
Use camelCase for form element names and change names like "label6" to something more indicative.

2021-11-19 12:27 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/AlphabotClientLibrary.Example.WinForms.csproj
> +</Project>
```suggestion
</Project>

```

2021-11-19 12:27 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/AlphabotClientLibrary.Example.WinForms.csproj.user
> +</Project>
```suggestion
</Project>

```

2021-11-19 12:27 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.resx
> +</root>
```suggestion
</root>

```

2021-12-03 17:15 UTC, Filiprogrammer requested changes

2021-12-03 17:15 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.cs
> +using System.Windows.Forms;
```suggestion
using System;
using System.Net;
using System.Threading;
using System.Windows.Forms;
﻿using AlphabotClientLibrary.Core;
using AlphabotClientLibrary.Core.Tcp;
using AlphabotClientLibrary.Shared.Contracts;
using AlphabotClientLibrary.Shared.Models;
using AlphabotClientLibrary.Shared.Requests;
```

2021-12-03 17:31 UTC, Filiprogrammer requested changes

2021-12-03 17:31 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.cs
> +        private void num_speed_ValueChanged(object sender, EventArgs e)
```suggestion
        private void numSpeed_ValueChanged(object sender, EventArgs e)
```

2021-12-03 17:31 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.cs
> +        private void tbar_steer_Scroll(object sender, EventArgs e)
```suggestion
        private void tbarSteer_Scroll(object sender, EventArgs e)
```

2021-12-03 17:31 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.cs
> +        private void btn_disconnect_Click(object sender, EventArgs e)
```suggestion
        private void btnDisconnect_Click(object sender, EventArgs e)
```

2021-12-03 17:31 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.cs
> +        private void btn_connect_Click(object sender, EventArgs e)
```suggestion
        private void btnConnect_Click(object sender, EventArgs e)
```

2021-12-03 17:31 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.Designer.cs
> +            this.btnConnect.Click += new System.EventHandler(this.btn_connect_Click);
```suggestion
            this.btnConnect.Click += new System.EventHandler(this.btnConnect_Click);
```

2021-12-03 17:31 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.Designer.cs
> +            this.btnDisconnect.Click += new System.EventHandler(this.btn_disconnect_Click);
```suggestion
            this.btnDisconnect.Click += new System.EventHandler(this.btnDisconnect_Click);
```

2021-12-03 17:31 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.Designer.cs
> +            this.tbarSteer.Scroll += new System.EventHandler(this.tbar_steer_Scroll);
```suggestion
            this.tbarSteer.Scroll += new System.EventHandler(this.tbarSteer_Scroll);
```

2021-12-03 17:31 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.Designer.cs
> +            this.numSpeed.ValueChanged += new System.EventHandler(this.num_speed_ValueChanged);
```suggestion
            this.numSpeed.ValueChanged += new System.EventHandler(this.numSpeed_ValueChanged);
```

2021-12-03 17:31 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.Designer.cs
> +            this.AccessibleDescription = "tbx_ip";
```suggestion
```

2021-12-03 17:31 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.Designer.cs
> +            this.tbxPort.AccessibleDescription = "tbx_port";
```suggestion
```

2021-12-03 17:31 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Example.WinForms/MainForm.Designer.cs
> +            this.tbxIp.AccessibleDescription = "tbx_ip";
```suggestion
```

2021-12-07 08:35 UTC, Filiprogrammer submitted a review, later dismissed

2021-12-08 14:23 UTC, merged