docs: Correct length of BLE toggle characteristic
Filiprogrammer/AlphabotSZUCar pull request #63
Opened 2021-12-09 13:46 UTC by Filiprogrammer

2021-12-09 14:30 UTC, LecraM2003 requested changes

2021-12-09 14:30 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +In the BLE protocol it is a characteristic which is 10 bytes in size.
```suggestion
In the BLE protocol it is a characteristic which is 10 bytes in size, because the timestamp (8 bytes) is sent right before the actual bit field (2 bytes)
```

2021-12-11 14:32 UTC, LecraM2003 approved these changes

2021-12-12 12:10 UTC, Filiprogrammer commented
#duration: 0.25

2021-12-12 12:10 UTC, merged