Refactor Alphabot.NET with present functionality
Filiprogrammer/AlphabotSZUCar pull request #66
Opened 2021-12-19 15:29 UTC by LecraM2003

Closes #49, #18 

Working Requests: Speed, Steer, Calibrate, Ping, Toggle (DoPositioning, LogPositioning, DoCollisionAvoidance)
Working Responses: Ping, Toggle (DoPositioning, LogPositioning, DoCollisionAvoidance), Positioning

Physically tested on Präsentationstag 17.12.2021 in school and 19.12.2021 at my home

2021-12-19 15:48 UTC, LecraM2003 commented
#duration: 14

2021-12-27 12:27 UTC, Filiprogrammer requested changes

2021-12-27 12:27 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Shared/SocketReader.cs
> +        public byte[] ReceiveBytes()
```suggestion

        public byte[] ReceiveBytes()
```

2021-12-27 12:27 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Shared/SocketReader.cs
> +        public byte[] ReceiveBytes()
Call ReceiveBytes from within ReceiveText to avoid duplication

2021-12-27 12:27 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Shared/Requests/PingRequest.cs
> +            return new byte[0];
Why does this return an empty array?

2021-12-27 12:27 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Shared/Contracts/IAlphabotRequest.cs
> +        public byte[] GetBytes();
```suggestion
        byte[] GetBytes();
```

2021-12-27 12:27 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Core/SessionHandler.cs
> +
```suggestion
```

2021-12-27 12:27 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Core/SessionHandler.cs
>          protected virtual void OnSessionClosed()
```suggestion
        public event EventHandler SessionClosed;

        protected virtual void OnSessionClosed()
```

2021-12-27 14:36 UTC, LecraM2003 commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionSetCollisionPrevention.cs
> +                    //  _car.StartCollisionPrevention();
the collision prevention is currently not working, if you call this method it throws an exception. temporarily it is commented out, until self drive is available

2021-12-27 14:36 UTC, LecraM2003 commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionSetCollisionPrevention.cs
> +                    // _car.StopCollisionPrevention();
the collision prevention is currently not working, if you call this method it throws an exception. temporarily it is commented out, until self drive is available

2021-12-27 14:43 UTC, LecraM2003 commented on rpi/Alphabot.Net/Alphabot.Net.Shared/Requests/PingRequest.cs
> +            return new byte[0];
because the method isnt called on the alphabot anyway, fixed that for you

2021-12-30 23:43 UTC, Filiprogrammer requested changes

2021-12-30 23:43 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionSetCollisionPrevention.cs
> +            Args[0] = Convert.ToInt32(preventCollision);
```suggestion
            Args = { Convert.ToInt32(preventCollision) };
```

2021-12-30 23:43 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionSetSpeed.cs
> +            Args[0] = speed;
```suggestion
            Args = { speed };
```

2021-12-30 23:43 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionSetSteeringMethod.cs
> +using System;
```suggestion
using System;
using Alphabot.Net.Car.Settings;
```

2021-12-30 23:43 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionSetSteeringMethod.cs
> +            Args[0] = Convert.ToInt32(isActiveSteering);
```suggestion
            Args = { Convert.ToInt32(isActiveSteering) };
```

2021-12-30 23:43 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Commands/ActionTurn.cs
> +            Args[0] = steer;
```suggestion
            Args = { steer };
```

2022-01-03 16:04 UTC, Filiprogrammer requested changes

2022-01-03 19:43 UTC, Filiprogrammer requested changes

2022-01-03 19:43 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Core/ActionExecutor.cs
> +        public ActionExecutor(IAlphabotRequest req, PositioningSystem.ResponseSender responseSender)
Why is the responseSender exclusive to the positioning system?

2022-01-03 19:44 UTC, Filiprogrammer commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Core/BitProtocolParser.cs
> +        public BitProtocolParser(byte[] bytes, PositioningSystem.ResponseSender responseSender)
Why is the responseSender exclusive to the positioning system?

2022-01-03 20:41 UTC, LecraM2003 commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Core/ActionExecutor.cs
> +        public ActionExecutor(IAlphabotRequest req, PositioningSystem.ResponseSender responseSender)
Created an external class where delegates are located

2022-01-03 20:42 UTC, LecraM2003 commented on rpi/Alphabot.Net/Alphabot.Net.Remote/Core/BitProtocolParser.cs
> +        public BitProtocolParser(byte[] bytes, PositioningSystem.ResponseSender responseSender)
Created an external class where delegates are located

2022-01-03 20:55 UTC, Filiprogrammer approved these changes

2022-01-03 21:16 UTC, merged