clients: Fix responses
Filiprogrammer/AlphabotSZUCar pull request #68
Opened 2021-12-19 15:59 UTC by LecraM2003

Closes #67 

Now where the Alphabot.NET understands the protocol, some bugs in the requests occurred, these will be fixed with that.

Bugs:
- Client crashes on TcpHandlerWindows.Disconnect() Method 
- PingResponse ctor sets the Latency negative instead of positive
- TcpResponseInterpreter throws an excpetion when wrong packet id is received
TO COMMIT? - for Xamarin .NET standard 2.0 is needed

2021-12-19 16:00 UTC, LecraM2003 commented
#duration: 3

2021-12-20 11:49 UTC, Filiprogrammer requested changes

2021-12-20 11:49 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpHandlerWindows.cs
> +                catch (Exception e)
Fix compiler warning that the variable 'e' is unused.
Also specify a more specific type of exception.

2021-12-20 11:49 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
> +            //throw new Exception("Received packet id is not valid");
Why?

2021-12-20 11:49 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/AlphabotClientLibrary.Core.Tcp.csproj
> +    <ProjectReference Include="..\AlphabotClientLibrary.Shared\AlphabotClientLibrary.Shared.csproj" />
Why?

2021-12-20 14:48 UTC, LecraM2003 commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpResponseInterpreter.cs
> +            //throw new Exception("Received packet id is not valid");
because, the packet header 0x00 gets sent when a connection ends, i will change that for more clearness

2021-12-20 18:22 UTC, Filiprogrammer requested changes

2021-12-20 18:22 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Core.Tcp/TcpHandlerWindows.cs
> +            _tcpClient.GetStream().Write(request.GetBytes(), 0, request.GetBytes().Length);
Do not call request.GetBytes() twice.

2021-12-21 11:12 UTC, Filiprogrammer approved these changes

2021-12-21 15:06 UTC, merged