docs/clients: Add missing sensor responses
Filiprogrammer/AlphabotSZUCar pull request #71
Opened 2021-12-20 14:43 UTC by LecraM2003

Closes #64 

Adds protocol documentation, code implementation and unit test cases for 5 new sensor responses:
- Wheel speed
- Anchor distances
- Accelerometer (IMU)
- Gyroscope (IMU)
- Magnetometer (IMU)

2021-12-20 14:45 UTC, LecraM2003 commented
#duration: 3.25

2021-12-21 21:14 UTC, Filiprogrammer requested changes

2021-12-21 21:14 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/MagnetometerResponse.cs
> +        /// The magnetic flux density in µT
Do not use non-ASCII characters
```suggestion
        /// The magnetic flux density in Microtesla
```

2021-12-21 21:14 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/MagnetometerResponse.cs
> +        /// The magnetic flux density in µT
Do not use non-ASCII characters
```suggestion
        /// The magnetic flux density in Microtesla
```

2021-12-21 21:14 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/MagnetometerResponse.cs
> +        /// The magnetic flux density in µT
Do not use non-ASCII characters
```suggestion
        /// The magnetic flux density in Microtesla
```

2021-12-21 21:43 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +| z-Axis     | int16      | The value of the z-Axis                                                                                                                 |
Wouldn't it be better to send all of the IMU sensor data at once?

2021-12-27 14:34 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +| z-Axis     | int16      | The value of the z-Axis                                                                                                                 |
no because maybe else you can not differentiate when one sensor is not available (alphabot with only 2 sensors for example)

2021-12-27 16:01 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +| Speed      | int8       | The speed of the wheels in m/s          |
I don't like it... it feels weird

2021-12-27 16:04 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +| Speed      | int8       | The speed of the wheels in m/s          |
After all, the sensor characteristic still has an unused sensor type.

2021-12-27 16:23 UTC, Filiprogrammer requested changes

2021-12-27 16:23 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            responseBytes = packetHeader.Concat(xBytes).Concat(yBytes).Concat(zBytes).ToArray();
```suggestion
            byte[] responseBytes = packetHeader.Concat(xBytes).Concat(yBytes).Concat(zBytes).ToArray();
```

2021-12-27 16:23 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            responseBytes = packetHeader.Concat(xBytes).Concat(yBytes).Concat(zBytes).ToArray();
```suggestion
            byte[] responseBytes = packetHeader.Concat(xBytes).Concat(yBytes).Concat(zBytes).ToArray();
```

2021-12-27 16:23 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            responseBytes = packetHeader.Concat(xBytes).Concat(yBytes).Concat(zBytes).ToArray();
```suggestion
            byte[] responseBytes = packetHeader.Concat(xBytes).Concat(yBytes).Concat(zBytes).ToArray();
```

2021-12-27 16:23 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Test/TcpResponseTest.cs
> +            Assert.InRange(accelerometerResponse.ZAxis, expectedZ - 0.1, expectedZ + 0.1);
```suggestion
            Assert.InRange(accelerometerResponse.XAxis, expectedX - 0.001, expectedX + 0.001);
            Assert.InRange(accelerometerResponse.YAxis, expectedY - 0.001, expectedY + 0.001);
            Assert.InRange(accelerometerResponse.ZAxis, expectedZ - 0.001, expectedZ + 0.001);
```

2021-12-27 16:23 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +| Z-axis     | int16      | The acceleration of the z-axis in m/s² * 1000 |
```suggestion
| X-axis     | int16      | The acceleration of the x-axis in m/s&#xB2; * 1000 |
| Y-axis     | int16      | The acceleration of the y-axis in m/s&#xB2; * 1000 |
| Z-axis     | int16      | The acceleration of the z-axis in m/s&#xB2; * 1000 |
```

2021-12-27 16:23 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +| Z-axis     | int16      | The magnetic flux density of the z-axis in µT * 10 |
```suggestion
| X-axis     | int16      | The magnetic flux density of the x-axis in &#xB5;T * 10 |
| Y-axis     | int16      | The magnetic flux density of the y-axis in &#xB5;T * 10 |
| Z-axis     | int16      | The magnetic flux density of the z-axis in &#xB5;T * 10 |
```

2021-12-27 18:36 UTC, Filiprogrammer requested changes

2021-12-27 18:36 UTC, Filiprogrammer commented on docs/wifi_ble_communication_protocol.md
> +### BLE_CHAR_IMU (UUID:93758afa-ce6f-4670-9562-ce92bda84d49)
```suggestion
### BLE_CHAR_IMU (UUID: 93758afa-ce6f-4670-9562-ce92bda84d49)
```

2021-12-28 20:48 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +| Speed      | int8       | The speed of the wheels in m/s          |
yeah i done it

2021-12-30 22:14 UTC, Filiprogrammer requested changes

2021-12-30 22:14 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/AccelerometerResponse.cs
> +using AlphabotClientLibrary.Shared.Models;
```suggestion
```

2021-12-30 22:14 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/AnchorDistancesResponse.cs
> +using AlphabotClientLibrary.Shared.Models;
```suggestion
```

2021-12-30 22:14 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/GyroscopeResponse.cs
> +using AlphabotClientLibrary.Shared.Models;
```suggestion
```

2021-12-30 22:14 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/MagnetometerResponse.cs
> +using AlphabotClientLibrary.Shared.Models;
```suggestion
```

2021-12-30 22:14 UTC, Filiprogrammer commented on clients/AlphabotClientLibrary/AlphabotClientLibrary.Shared/Responses/WheelSpeedResponse.cs
> +using AlphabotClientLibrary.Shared.Models;
```suggestion
```

2022-01-01 16:09 UTC, Filiprogrammer approved these changes

2022-01-01 18:14 UTC, Filiprogrammer approved these changes

2022-01-01 18:17 UTC, merged