docs/protocol: Remove duplicate calibration request
Filiprogrammer/AlphabotSZUCar pull request #72
Opened 2021-12-25 12:51 UTC by Filiprogrammer

Remove the compass calibration setting from the settings bit field,
as the compass can already be calibrated in another way.

2021-12-27 14:28 UTC, LecraM2003 requested changes
Let the "not used" bit at bit 3, so it is consistant

2021-12-27 14:28 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +| Bit 7 (MSB) | Bit 6  | Bit 5       | Bit 4               | Bit 3           | Bit 2        | Bit 1    | Bit 0 (LSB) |
```suggestion
| Bit 7 (MSB) | Bit 6       | Bit 5               | Bit 4           | Bit 3        | Bit 2    | Bit 1    | Bit 0 (LSB) |
```

2021-12-27 14:28 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +|-------------|--------|-------------|---------------------|-----------------|--------------|----------|-------------|
```suggestion
|-------------|-------------|---------------------|-----------------|--------------|----------|----------|-------------|
```

2021-12-27 14:28 UTC, LecraM2003 commented on docs/wifi_ble_communication_protocol.md
> +| not used    | Invite | Positioning | Collision Avoidance | Navigation-Mode | Explore-Mode | not used | not used    |
```suggestion
| Invite      | Positioning | Collision Avoidance | Navigation-Mode | Explore-Mode | not used | not used | not used    |
```

2021-12-27 14:29 UTC, LecraM2003 commented
Also create an issue, where the protocol changes are adapted in client library and Alphabot.NET

2021-12-27 15:40 UTC, Filiprogrammer commented
#duration: 1

2021-12-28 19:26 UTC, LecraM2003 approved these changes

2021-12-29 13:10 UTC, merged